# Generated by Django 3.2.9 on 2021-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer'), ('ANALYST', 'Analyst'), ('CUSTOMER', 'Customer')], db_index=True, max_length=20),
        ),
    ]
