# Generated by Django 3.2.9 on 2021-11-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211103_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=10)),
                ('article_type', models.CharField(choices=[('FAQ', 'FAQ'), ('ARTICLE', 'Article')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('Content', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
