# Generated by Django 3.2.9 on 2021-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
