# Generated by Django 3.2.9 on 2021-11-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_content_document_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentFile',
        ),
    ]
